version: "3.9"

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./:/app
    depends_on:
      - db
  
volumes:
  postgres_data: